import React, { useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { FileText, Download, Plus } from 'lucide-react';
import { toast } from 'sonner';
import type { ReportItem } from '../types';
import { useAppStore } from '../store/useAppStore';
import { Table } from '../components/ui/Table';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Modal } from '../components/ui/Modal';
import { Select } from '../components/ui/Select';
import { Input } from '../components/ui/Input';

export const ReportsPage: React.FC = () => {
  const { reports, generateReport } = useAppStore();
  const [isModalOpen, setIsModalOpen] = useState(false);

  const [title, setTitle] = useState('');
  const [reportType, setReportType] = useState<ReportItem['type']>('occupancy');
  const [period] = useState('July 2026');

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) {
      toast.error('Please enter report title');
      return;
    }
    generateReport(title, reportType, period);
    toast.success(`Report generated: ${title}`);
    setIsModalOpen(false);
  };

  const columns: ColumnDef<ReportItem>[] = [
    {
      accessorKey: 'title',
      header: 'REPORT TITLE',
      cell: ({ row }) => (
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-blue-50 text-brandBlue shrink-0">
            <FileText className="w-4 h-4" />
          </div>
          <div className="min-w-0">
            <div className="font-bold text-navy text-sm truncate max-w-sm">{row.original.title}</div>
            <div className="text-[11px] text-slate-400 truncate">{row.original.period} • {row.original.recordCount} records</div>
          </div>
        </div>
      ),
    },
    {
      accessorKey: 'type',
      header: 'CATEGORY',
      cell: ({ row }) => <span className="text-xs uppercase font-bold text-slate-500">{row.original.type}</span>,
    },
    {
      accessorKey: 'generatedAt',
      header: 'GENERATED DATE',
      cell: ({ row }) => <span className="text-xs text-slate-600 font-mono">{row.original.generatedAt}</span>,
    },
    {
      accessorKey: 'generatedBy',
      header: 'GENERATED BY',
      cell: ({ row }) => <span className="text-xs font-semibold text-slate-700">{row.original.generatedBy}</span>,
    },
    {
      accessorKey: 'fileSize',
      header: 'FILE SIZE',
      cell: ({ row }) => <span className="text-xs text-slate-500 font-mono">{row.original.fileSize}</span>,
    },
    {
      id: 'actions',
      header: '',
      cell: ({ row }) => (
        <Button
          variant="outline"
          size="sm"
          leftIcon={<Download className="w-3.5 h-3.5" />}
          onClick={() => toast.success(`Downloading ${row.original.title}...`)}
        >
          Download PDF
        </Button>
      ),
    },
  ];

  return (
    <div className="space-y-8">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-navy">Reports Center</h2>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">Generate, export, and download comprehensive library operational audit reports.</p>
        </div>
        <div className="flex items-center gap-3">
          <Button
            variant="primary"
            size="sm"
            onClick={() => setIsModalOpen(true)}
            leftIcon={<Plus className="w-4 h-4" />}
          >
            Generate New Report
          </Button>
        </div>
      </div>

      {/* Generated Reports Repository Table */}
      <Card title="Past Generated Reports" subtitle="Repository of downloadable library operational analytics">
        <Table columns={columns} data={reports} pageSize={8} />
      </Card>

      {/* Generate Report Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Generate Operational Report"
        subtitle="Configure report scope, date range, and export settings"
        footer={
          <>
            <Button variant="outline" size="sm" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="primary" size="sm" onClick={handleGenerate}>
              Generate Report
            </Button>
          </>
        }
      >
        <form className="space-y-4">
          <Input
            label="Report Title *"
            placeholder="e.g. August Weekly Occupancy Audit"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />

          <div className="grid grid-cols-2 gap-4">
            <Select
              label="Report Category *"
              options={[
                { value: 'occupancy', label: 'Seat Occupancy Summary' },
                { value: 'noshow', label: 'No-Show Violations Audit' },
                { value: 'peakhours', label: 'Peak Hours Load Analysis' },
                { value: 'staff_activity', label: 'Staff Verification Audit' },
              ]}
              value={reportType}
              onChange={(e) => setReportType(e.target.value as any)}
            />

            <Select
              label="Format Target *"
              options={[
                { value: 'pdf', label: 'PDF Document (.pdf)' },
                { value: 'csv', label: 'CSV Spreadsheet (.csv)' },
                { value: 'excel', label: 'Excel Workbook (.xlsx)' },
              ]}
            />
          </div>
        </form>
      </Modal>
    </div>
  );
};
